# Generated by Django 2.0.7 on 2018-07-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapplist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.ForeignKey(default='general', null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapplist.Category'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(default='18-07-17'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateTimeField(default='18-07-17'),
        ),
    ]
