# Generated by Django 2.0.7 on 2018-07-19 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapplist', '0003_auto_20180717_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=datetime.date(2018, 7, 19)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(help_text='Enter the date in the formatt YYYY-MM-DD'),
        ),
    ]
