# Generated by Django 2.0.7 on 2018-07-26 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapplist', '0004_auto_20180719_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=datetime.date(2018, 7, 26)),
        ),
    ]
